name: Frontend rewrite CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: './clientRewrite'

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Run Type Check
        run: yarn typecheck

      - name: Run ESLint
        run: yarn lint

      - name: Check formatting
        run: yarn formatcheck

      - name: Run Tests
        run: yarn coverage

      - name: Comment coverage
        uses: MishaKav/jest-coverage-comment@main
        with:
          coverage-summary-path: ./coverage/coverage-final.json