name: "Terraform Infrastructure Change Management"

on:
  push:
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"
    branches: 
      - master
  pull_request:
    paths:
      - "infra/**"
      - ".github/workflows/terraform.yml"
    branches: 
      - master

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        working-directory: './infra'
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

#    - uses: terraform-linters/setup-tflint@v3
#      name: Setup TFLint
#      with:
#        tflint_version: latest
#
#    - name: Show version
#      run: tflint --version
#    
#    - name: Init TFLint
#      run: tflint --init
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     # Install the latest version of Terraform CLI and configure the Terraform CLI configuration.
    - name: Install Terraform
      run: |
        wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
        sudo apt update && sudo apt install terraform
          
    - name: Terraform Init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        AWS_REGION: "eu-north-1"
      run: terraform init

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt
    
#    - name: Terraform lint
#      run: tflint 

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        AWS_REGION: "eu-north-1"
      run: terraform plan -var="postgres_user=${{secrets.PROD_DB_USERNAME}}" -var="postgres_pass=${{secrets.PROD_DB_PASSWORD}}" -var="postgres_db=stagnum" -var="aws_access_key=${{secrets.AWS_ACCESS_KEY_ID}}" -var="aws_secret_key=${{secrets.AWS_ACCESS_KEY_SECRET}}" -var="spotify_client_id=${{secrets.SPOTIFY_CLIENT_ID}}" -var="spotify_client_secret=${{secrets.SPOTIFY_CLIENT_SECRET}}"

      # On push to "main", build or change infrastructure according to Terraform configuration files
      # Note: It is recommended to set up a required "strict" status check in your repository for "Terraform Cloud". See the documentation on "strict" required status checks for more information: https://help.github.com/en/github/administering-a-repository/types-of-required-status-checks
    - name: Terraform Apply
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        AWS_REGION: "eu-north-1"
      run: terraform apply -auto-approve -input=false -var="postgres_user=${{secrets.PROD_DB_USERNAME}}" -var="postgres_pass=${{secrets.PROD_DB_PASSWORD}}" -var="postgres_db=stagnum" -var="aws_access_key=${{secrets.AWS_ACCESS_KEY_ID}}" -var="aws_secret_key=${{secrets.AWS_ACCESS_KEY_SECRET}}" -var="spotify_client_id=${{secrets.SPOTIFY_CLIENT_ID}}" -var="spotify_client_secret=${{secrets.SPOTIFY_CLIENT_SECRET}}"

#    - name: Terraform destroy
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
#      run: terraform destroy -auto-approve -input=false

    - name: Commit automatic cleans
      uses: stefanzweifel/git-auto-commit-action@v5
      with: 
        commit_message: Apply formatting changes
        branch: ${{ github.head_ref }}